"""Add proof_verified column to Report model

Revision ID: f636f8235f37
Revises: 9359b935b6e3
Create Date: 2025-04-19 17:26:01.423355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f636f8235f37'
down_revision = '9359b935b6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('proof_verified')

    # ### end Alembic commands ###
